#!/bin/bash
# ====== COLORS ======
COL_BLACK="\x1b[30;01m"
COL_RED="\x1b[31;01m"
COL_GREEN="\x1b[32;01m"
COL_YELLOW="\x1b[33;01m"
COL_MAGENTA="\x1b[35;01m"
COL_CYAN="\x1b[36;01m"
COL_WHITE="\x1b[37;01m"
COL_BLUE="\x1b[34;01m"
COL_RESET="\x1b[39;49;00m"

# ====== BASE URL & VERSION ======
# リポジトリのRawファイルのベースURLとバージョン変数
BASE_URL="https://github.com/mifjpn/Kawaiintu-yet-another-moebuntu-MifjpnsOriginal/raw/main"
VER="2604"

# ====== theme urls ======
ThemePink="${BASE_URL}/themes/Kawaiintu-Pink${VER}.tar.xz"
ThemeBlue="${BASE_URL}/themes/Kawaiintu-Blue${VER}.tar.xz"
ThemeCyan="${BASE_URL}/themes/Kawaiintu-Cyan${VER}.tar.xz"
ThemeGreen="${BASE_URL}/themes/Kawaiintu-Green${VER}.tar.xz"
ThemeLime="${BASE_URL}/themes/Kawaiintu-Lime${VER}.tar.xz"
ThemeOrange="${BASE_URL}/themes/Kawaiintu-Orange${VER}.tar.xz"
ThemePurple="${BASE_URL}/themes/Kawaiintu-Purple${VER}.tar.xz"
ThemeRed="${BASE_URL}/themes/Kawaiintu-Red${VER}.tar.xz"
ThemeRose="${BASE_URL}/themes/Kawaiintu-Rose${VER}.tar.xz"

# ====== Sound URL ======
Soundiori="${BASE_URL}/sound/Moesound_iori.tar.gz"
Soundmaid_iori="${BASE_URL}/sound/Moesound_maid_iori.tar.gz"
SoundSF_iori="${BASE_URL}/sound/Moesound_SF_iori.tar.gz"
SoundMGd="${BASE_URL}/sound/Moesound_MGd.tar.gz"

menu() {
clear
echo -e $COL_GREEN" ------------------------------------------------------------------------------"
echo -e "$COL_GREEN                    Kawaiintu Setting Helper for 26.04Lts"
echo -e $COL_GREEN" ------------------------------------------------------------------------------"$COL_RESET
PS3='Please enter your choice: '
options=( 'base setting(Do first!)'
          'set theme Pink'
          'set theme Blue'
          'set theme Cyan'
          'set theme Green'
          'set theme Lime'
          'set theme Orange'
          'set theme Purple'
          'set theme Red'
          'set theme Rose'
          'remove Kawaiintu-theme'
          'set Kawaiintu-Icons'
          'remove Kawaiintu-Icons'
          'set Kawaiintu-spinner plymouth'
          'remove Kawaiintu-spinner plymouth'
          'set Kawaiintu Wallpaper'
          'remove Kawaiintu Wallpaper'
          'firefox to deb package'
          'firefox to snap package'
          'add nemo'
          'remove nemo'
          'add thunar'
          'remove thunar'
          'add vlc(deb)'
          'remove vlc(deb)'
          'set Moesound_iori'
          'set Moesound_maid_iori'
          'set Moesound_SF_iori'
          'set Moesound_MGd'
          'remove Moesound'
          'quit')

select opt in "${options[@]}"
do
  case $opt in
    "base setting(Do first!)")
      /bin/bash ./install-GSM;
      break
    ;;
    "set theme Pink")
      /bin/bash ./set-theme $ThemePink ;
      break
    ;;
    "set theme Blue")
      /bin/bash ./set-theme $ThemeBlue ;
      break
    ;;
    "set theme Cyan")
      /bin/bash ./set-theme $ThemeCyan ;
      break
    ;;
    "set theme Green")
      /bin/bash ./set-theme $ThemeGreen ;
      break
    ;;
    "set theme Lime")
      /bin/bash ./set-theme $ThemeLime ;
      break
    ;;
    "set theme Orange")
      /bin/bash ./set-theme $ThemeOrange ;
      break
    ;;
    "set theme Purple")
      /bin/bash ./set-theme $ThemePurple ;
      break
    ;;
    "set theme Red")
      /bin/bash ./set-theme $ThemeRed ;
      break
    ;;
    "set theme Rose")
      /bin/bash ./set-theme $ThemeRose ;
      break
    ;;
    "remove Kawaiintu-theme")
      /bin/bash ./theme2defalt ;
      break
    ;;
    "set Kawaiintu-Icons")
      /bin/bash ./iconmanager install ;
      break
    ;;
    "remove Kawaiintu-Icons")
      /bin/bash ./iconmanager remove ;
      break
    ;;
    "set Kawaiintu-spinner plymouth")
      /bin/bash ./set-plymouth ;
      break
    ;;
    "remove Kawaiintu-spinner plymouth")
      /bin/bash ./plymouth2default ;
      break
    ;;
    "set Kawaiintu Wallpaper")
      /bin/bash ./wallmanager install ;
      break
    ;;
    "remove Kawaiintu Wallpaper")
      /bin/bash ./wallmanager remove ;
      break
    ;;
    "firefox to deb package")
      /bin/bash ./firefox2deb ;
      break
    ;;
    "firefox to snap package")
      /bin/bash ./firefox2snap ;
      break
    ;;
    "add nemo")
      /bin/bash ./addnemo;
      break
    ;;
    "remove nemo")
      /bin/bash ./removenemo ;
      break
    ;;
    "add thunar")
      /bin/bash ./addthunar;
      break
    ;;
    "remove thunar")
      /bin/bash ./removethunar ;
      break
    ;;
    "add vlc(deb)")
      /bin/bash ./addvlc;
      break
    ;;
    "remove vlc(deb)")
      /bin/bash ./removevlc ;
      break
    ;;
    "set Moesound_iori")
      /bin/bash ./setsound $Soundiori ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "set Moesound_maid_iori")
      /bin/bash ./setsound $Soundmaid_iori ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "set Moesound_SF_iori")
      /bin/bash ./setsound $SoundSF_iori ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "set Moesound_MGd")
      /bin/bash ./setsound $SoundMGd ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "remove Moesound")
      /bin/bash ./removesound ;
      /bin/bash ./loginsound remove ;
      break
    ;;
    "quit")
      exit 0
    ;;
    *)
      echo "invalid option $REPLY"
      break
    ;;
  esac
done
menu
}

## main
menu
