#!/bin/bash
# ====== COLORS ======
COL_BLACK="\x1b[30;01m"
COL_RED="\x1b[31;01m"
COL_GREEN="\x1b[32;01m"
COL_YELLOW="\x1b[33;01m"
COL_MAGENTA="\x1b[35;01m"
COL_CYAN="\x1b[36;01m"
COL_WHITE="\x1b[37;01m"
COL_BLUE="\x1b[34;01m"
COL_RESET="\x1b[39;49;00m"

# ====== BASE URL & VERSION ======
# Base URL for repository Raw files and version variables
BASE_URL="https://github.com/mifjpn/Kawaiintu-yet-another-moebuntu-MifjpnsOriginal/raw/main"
VER="2604"

# ====== theme urls ======
ThemePink="${BASE_URL}/themes/kawaiintu-pink${VER}.tar.xz"
ThemeBlue="${BASE_URL}/themes/kawaiintu-blue${VER}.tar.xz"
ThemeCyan="${BASE_URL}/themes/kawaiintu-cyan${VER}.tar.xz"
ThemeGreen="${BASE_URL}/themes/kawaiintu-green${VER}.tar.xz"
ThemeLime="${BASE_URL}/themes/kawaiintu-lime${VER}.tar.xz"
ThemeOrange="${BASE_URL}/themes/kawaiintu-orange${VER}.tar.xz"
ThemePurple="${BASE_URL}/themes/kawaiintu-purple${VER}.tar.xz"
ThemeRed="${BASE_URL}/themes/kawaiintu-red${VER}.tar.xz"
ThemeRose="${BASE_URL}/themes/kawaiintu-rose${VER}.tar.xz"

# ====== Sound URL ======
Soundiori="${BASE_URL}/sound/Moesound_iori.tar.gz"
Soundmaid_iori="${BASE_URL}/sound/Moesound_maid_iori.tar.gz"
SoundSF_iori="${BASE_URL}/sound/Moesound_SF_iori.tar.gz"
SoundMGd="${BASE_URL}/sound/Moesound_MGd.tar.gz"

# ====== Firefox UI Auto-Config ======
fix_firefox_titlebar() {
    echo -e "${COL_CYAN}[*] Configuring Firefox UI for Kawaiintu...${COL_RESET}"
    REAL_USER=${SUDO_USER:-$USER}
    USER_HOME=$(eval echo ~$REAL_USER)
    
    # Search all 3 profile patterns: legacy (.mozilla), Snap, and new standard (.config)
    for profile in "$USER_HOME/.mozilla/firefox/"*.default* \
                   "$USER_HOME/snap/firefox/common/.mozilla/firefox/"*.default* \
                   "$USER_HOME/.config/mozilla/firefox/"*.default*; do
        if [ -d "$profile" ]; then
            if [ -f "$profile/user.js" ]; then
                # Remove duplicate old settings
                sed -i '/browser.tabs.inTitlebar/d' "$profile/user.js"
                sed -i '/extensions.activeThemeID/d' "$profile/user.js"
            fi
            
            # 1. Show title bar (use system frame)
            echo 'user_pref("browser.tabs.inTitlebar", 0);' >> "$profile/user.js"
            
            # 2. Force theme to Follow system theme (default)
            echo 'user_pref("extensions.activeThemeID", "default-theme@mozilla.org");' >> "$profile/user.js"
            
            # Restore permissions to normal user
            chown "$REAL_USER:$REAL_USER" "$profile/user.js"
        fi
    done
}

menu() {
clear
echo -e $COL_GREEN" ------------------------------------------------------------------------------"
echo -e "$COL_GREEN                    Kawaiintu Setting Helper for 26.04Lts"
echo -e $COL_GREEN" ------------------------------------------------------------------------------"$COL_RESET
PS3='Please enter your choice: '
options=( 'base setting(Do first!)'
          'set theme Pink'
          'set theme Blue'
          'set theme Cyan'
          'set theme Green'
          'set theme Lime'
          'set theme Orange'
          'set theme Purple'
          'set theme Red'
          'set theme Rose'
          'remove Kawaiintu-theme'
          'set Kawaiintu-Icons'
          'remove Kawaiintu-Icons'
          'set Kawaiintu-spinner plymouth'
          'remove Kawaiintu-spinner plymouth'
          'set Kawaiintu Wallpaper'
          'remove Kawaiintu Wallpaper'
          'firefox to deb package'
          'firefox to snap package'
          'add nemo'
          'remove nemo'
          'add thunar'
          'remove thunar'
          'add parole(Video Player)'
          'remove parole(Video Player)'
          'add tilix'
          'remove tilix'
          'add gedit'
          'remove gedit'
          'set Moesound_iori'
          'set Moesound_maid_iori'
          'set Moesound_SF_iori'
          'set Moesound_MGd'
          'remove Moesound'
          'quit')

select opt in "${options[@]}"
do
  case $opt in
    "base setting(Do first!)")
      /bin/bash ./install-GSM;
      break
    ;;
    "set theme Pink")
      /bin/bash ./set-theme $ThemePink ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Blue")
      /bin/bash ./set-theme $ThemeBlue ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Cyan")
      /bin/bash ./set-theme $ThemeCyan ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Green")
      /bin/bash ./set-theme $ThemeGreen ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Lime")
      /bin/bash ./set-theme $ThemeLime ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Orange")
      /bin/bash ./set-theme $ThemeOrange ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Purple")
      /bin/bash ./set-theme $ThemePurple ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Red")
      /bin/bash ./set-theme $ThemeRed ;
      fix_firefox_titlebar ;
      break
    ;;
    "set theme Rose")
      /bin/bash ./set-theme $ThemeRose ;
      fix_firefox_titlebar ;
      break
    ;;
    "remove Kawaiintu-theme")
      /bin/bash ./theme2defalt ;
      break
    ;;
    "set Kawaiintu-Icons")
      /bin/bash ./iconmanager install ;
      break
    ;;
    "remove Kawaiintu-Icons")
      /bin/bash ./iconmanager remove ;
      break
    ;;
    "set Kawaiintu-spinner plymouth")
      /bin/bash ./set-plymouth ;
      break
    ;;
    "remove Kawaiintu-spinner plymouth")
      /bin/bash ./plymouth2default ;
      break
    ;;
    "set Kawaiintu Wallpaper")
      /bin/bash ./wallmanager install ;
      break
    ;;
    "remove Kawaiintu Wallpaper")
      /bin/bash ./wallmanager remove ;
      break
    ;;
    "firefox to deb package")
      /bin/bash ./firefox2deb ;
      fix_firefox_titlebar ;
      break
    ;;
    "firefox to snap package")
      /bin/bash ./firefox2snap ;
      fix_firefox_titlebar ;
      break
    ;;
    "add nemo")
      /bin/bash ./addnemo;
      break
    ;;
    "remove nemo")
      /bin/bash ./removenemo ;
      break
    ;;
    "add thunar")
      /bin/bash ./addthunar;
      break
    ;;
    "remove thunar")
      /bin/bash ./removethunar ;
      break
    ;;
    "add parole(Video Player)")
      /bin/bash ./addparole;
      break
    ;;
    "remove parole(Video Player)")
      /bin/bash ./removeparole ;
      break
    ;;
    "add tilix")
      /bin/bash ./addtilix ;
      break
    ;;
    "remove tilix")
      # Check if dependencies (Nemo/Thunar) exist before removing Tilix
      if command -v nemo >/dev/null 2>&1 || command -v thunar >/dev/null 2>&1; then
          echo -e "\n${COL_RED}[!] Error: Cannot remove Tilix right now.${COL_RESET}"
          echo -e "${COL_YELLOW}Nemo or Thunar is currently installed and depends on Tilix for terminal functions.${COL_RESET}"
          echo -e "${COL_YELLOW}Please remove them explicitly from the menu first before removing Tilix.${COL_RESET}\n"
          echo -n "Hit Any Key to return to menu: "
          read -r -n 1 -s answer
          echo ""
      else
          /bin/bash ./removetilix ;
      fi
      break
    ;;
    "add gedit")
      /bin/bash ./addgedit ;
      break
    ;;
    "remove gedit")
      /bin/bash ./removegedit ;
      break
    ;;
    "set Moesound_iori")
      /bin/bash ./setsound $Soundiori ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "set Moesound_maid_iori")
      /bin/bash ./setsound $Soundmaid_iori ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "set Moesound_SF_iori")
      /bin/bash ./setsound $SoundSF_iori ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "set Moesound_MGd")
      /bin/bash ./setsound $SoundMGd ;
      /bin/bash ./loginsound install ;
      break
    ;;
    "remove Moesound")
      /bin/bash ./removesound ;
      /bin/bash ./loginsound remove ;
      break
    ;;
    "quit")
      exit 0
    ;;
    *)
      echo "invalid option $REPLY"
      break
    ;;
  esac
done
menu
}

## main
menu
